### ISSUE TITLE
Hacktoberfest 2018

### ISSUE THREAD

**Issue by abaykan** [abaykan/hacktoberfest#4]
Hi All, old or new Hacktoberfest contributors!

This repository was initially created for the 2018 Hacktoberfest as a half joke, half serious census.

So, to all of you who want to contribute to this project...

You can check this to know how to contribute > https://github.com/abaykan/hacktoberfest

I would encourage everyone who participates in this project to not count it as one of your five Open Source contributions, due to it's simplistic nature, although obviously I can't stop you.

Have a great Hacktoberfest and Happy Hacking!

**Comment by dgavio** [comment]
Hi, how can we contribute to this project?

**Comment by abaykan** [comment]
> Hi, how can we contribute to this project?

You can check this to know how to contribute > https://github.com/abaykan/hacktoberfest
